### ISSUE TITLE
Generate validation from OpenAPI Spec - as described in README

### ISSUE THREAD

**Issue by bastianwegge** [fabien0102/openapi-codegen#148]
Hello 👋 ,

I just found this awesome repo and I'm wondering about the generation of validation from OpenAPI Spec. In the README there's a paragraph stating:

```yaml
SignUpInput:
  type: object
  properties:
    ...
    firstName:
      type: string
      pattern: ^[0-9a-zA-Z]*$
      maxLength: 255
    ...
  required:
    ...
    - firstName
    ...
```
> OpenAPI Codegen will be able to generate all the relevant validation (or at least give you the choice to do it).

As I was playing around with the generation of this specific example, I generated the following result:

```
  /**
   * @pattern ^[0-9a-zA-Z]*$
   * @maxLength 255
   */
  code: string;
```

It picks up the `required` state into the type itself and the documentation inside of the type is copied from the OpenAPI spec as you can see below. Am I missing something very obvious or did I just misread the part where the README says "... generate all the relevant validation ..."?
