### ISSUE TITLE
[Issue] running openapi-codegen in github actions

### ISSUE THREAD

**Issue by kev2480** [fabien0102/openapi-codegen#296]
Issue I'm seeing after running `npx openapi-codegen gen apiClient` in github actions

```
node:fs:453
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/home/runner/.npm/_npx/d0626b3472b240bf/node_modules/openapi-codegen/configs/gen.json'
    at Object.readFileSync (node:fs:453:20)
    at Object.<anonymous> (/home/runner/.npm/_npx/d0626b3472b240bf/node_modules/openapi-codegen/cg.js:80:62)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:10[23](https://github.com/3sidedcube-orca/psma-web/actions/runs/13269446482/job/37045377640#step:4:24):12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:135:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/runner/.npm/_npx/d0626b3472b[24](https://github.com/3sidedcube-orca/psma-web/actions/runs/13269446482/job/37045377640#step:4:25)0bf/node_modules/openapi-codegen/configs/gen.json'
}
```

<img width="1672" alt="Image" src="https://github.com/user-attachments/assets/bad3b592-b0fa-4713-89cc-3fc4f7e752ef" />

## This is my config:

```
import { generateSchemaTypes, generateReactQueryComponents } from "@openapi-codegen/typescript";
import { defineConfig } from "@openapi-codegen/cli";
import * as dotenv from "dotenv";

dotenv.config();

console.log("API Endpoint", process.env.API_ENDPOINT);

export default defineConfig({
  apiClient: {
    from: {
      source: "url",
      url: `${process.env.API_ENDPOINT}/dev/api-yaml`
    },
    outputDir: "src/generated/api",
    to: async context => {
      const filenamePrefix = "apiClient";
      const { schemasFiles } = await generateSchemaTypes(context, {
        filenamePrefix
      });
      await generateReactQueryComponents(context, {
        filenamePrefix,
        schemasFiles
      });
    }
  }
});
```

## Github Action Job

```
  build:
    name: Build Project
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.0
          cache: "npm"
      - name: Build and Test
        run: |
          npm run api:generate
          npm run test
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/
            coverage/
```

`npm run api:generate` script is just `npx openapi-codegen gen apiClient`
