### ISSUE TITLE
Example of using FetcherOptions (or something else) to set request URL?

### ISSUE THREAD

**Issue by xgp** [fabien0102/openapi-codegen#74]
Apologies if this is the wrong place to post, but I am having trouble understanding how I can set some variables in the request URL.

In my openapi spec file (https://github.com/p2-inc/phasetwo-docs/blob/master/openapi.yaml), I have a `servers` section that looks like this:
```
servers:
  - url: '{protocol}://{host}{port}/auth/realms'
    variables:
      host:
        enum:
          - app.phasetwo.io
          - localhost
        default: app.phasetwo.io
        description: API host
      port:
        enum:
          - ''
          - '8081'
        default: ''
        description: API port
      protocol:
        enum:
          - http
          - https
        default: https
```

In my orgsFetchers.ts, it creates a `baseUrl` template like this:
```
const baseUrl = '{protocol}://{host}{port}/auth/realms';
```
which looks like it gets rendered here:
```
    const response = await window.fetch(`${baseUrl}${resolveUrl(url, queryParams, pathParams)}`, {
```

I'm able to set `pathParams` like this:
```
  const { data, error, isLoading } = useGetOrganizations({pathParams: {realm:'self'}});
```
but I can't figure out how to set anything in the `baseUrl`. Furthermore, the URL that ends up getting called, uses the host of the app as a prefix:
```
http://localhost:9000/%7Bprotocol%7D://%7Bhost%7D%7Bport%7D/auth/realms/self/orgs
```

So, two questions:
1. how to set the parameters in the `baseUrl`?
2. how to have the fetcher use the `baseUrl` without the host of the app as the prefix?

Thanks!
